services:
  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:0.11.11
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8g

  agents:
    build: ./agents
    container_name: agents
    env_file:
      - .env
    volumes:
      - ./agents/src:/app
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - ollama
      - qdrant

  indexing:
    build: ./indexing
    container_name: indexing
    env_file:
      - .env
    volumes:
      - ./indexing/src:/app
      - ./qdrant_storage:/qdrant/storage
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - ollama
      - qdrant

volumes:
  qdrant_data: